// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	models "atlas-bob-practice/models"
	"github.com/aarondl/opt/omit"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type TaskMod interface {
	Apply(context.Context, *TaskTemplate)
}

type TaskModFunc func(context.Context, *TaskTemplate)

func (f TaskModFunc) Apply(ctx context.Context, n *TaskTemplate) {
	f(ctx, n)
}

type TaskModSlice []TaskMod

func (mods TaskModSlice) Apply(ctx context.Context, n *TaskTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// TaskTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type TaskTemplate struct {
	ID        func() int64
	Name      func() string
	UserID    func() int64
	CreatedAt func() time.Time
	UpdatedAt func() time.Time

	r taskR
	f *Factory

	alreadyPersisted bool
}

type taskR struct {
	User *taskRUserR
}

type taskRUserR struct {
	o *UserTemplate
}

// Apply mods to the TaskTemplate
func (o *TaskTemplate) Apply(ctx context.Context, mods ...TaskMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Task
// according to the relationships in the template. Nothing is inserted into the db
func (t TaskTemplate) setModelRels(o *models.Task) {
	if t.r.User != nil {
		rel := t.r.User.o.Build()
		rel.R.Tasks = append(rel.R.Tasks, o)
		o.UserID = rel.ID // h2
		o.R.User = rel
	}
}

// BuildSetter returns an *models.TaskSetter
// this does nothing with the relationship templates
func (o TaskTemplate) BuildSetter() *models.TaskSetter {
	m := &models.TaskSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.Name != nil {
		val := o.Name()
		m.Name = omit.From(val)
	}
	if o.UserID != nil {
		val := o.UserID()
		m.UserID = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.TaskSetter
// this does nothing with the relationship templates
func (o TaskTemplate) BuildManySetter(number int) []*models.TaskSetter {
	m := make([]*models.TaskSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Task
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use TaskTemplate.Create
func (o TaskTemplate) Build() *models.Task {
	m := &models.Task{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Name != nil {
		m.Name = o.Name()
	}
	if o.UserID != nil {
		m.UserID = o.UserID()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.TaskSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use TaskTemplate.CreateMany
func (o TaskTemplate) BuildMany(number int) models.TaskSlice {
	m := make(models.TaskSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableTask(m *models.TaskSetter) {
	if !(m.Name.IsValue()) {
		val := random_string(nil, "20")
		m.Name = omit.From(val)
	}
	if !(m.UserID.IsValue()) {
		val := random_int64(nil)
		m.UserID = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Task
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *TaskTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Task) error {
	var err error

	return err
}

// Create builds a task and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *TaskTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Task, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableTask(opt)

	if o.r.User == nil {
		TaskMods.WithNewUser().Apply(ctx, o)
	}

	var rel0 *models.User

	if o.r.User.o.alreadyPersisted {
		rel0 = o.r.User.o.Build()
	} else {
		rel0, err = o.r.User.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.UserID = omit.From(rel0.ID)

	m, err := models.Tasks.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.User = rel0

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a task and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *TaskTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Task {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a task and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *TaskTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Task {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple tasks and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o TaskTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.TaskSlice, error) {
	var err error
	m := make(models.TaskSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple tasks and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o TaskTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.TaskSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple tasks and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o TaskTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.TaskSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Task has methods that act as mods for the TaskTemplate
var TaskMods taskMods

type taskMods struct{}

func (m taskMods) RandomizeAllColumns(f *faker.Faker) TaskMod {
	return TaskModSlice{
		TaskMods.RandomID(f),
		TaskMods.RandomName(f),
		TaskMods.RandomUserID(f),
		TaskMods.RandomCreatedAt(f),
		TaskMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m taskMods) ID(val int64) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.ID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m taskMods) IDFunc(f func() int64) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m taskMods) UnsetID() TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m taskMods) RandomID(f *faker.Faker) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.ID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m taskMods) Name(val string) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.Name = func() string { return val }
	})
}

// Set the Column from the function
func (m taskMods) NameFunc(f func() string) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m taskMods) UnsetName() TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m taskMods) RandomName(f *faker.Faker) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.Name = func() string {
			return random_string(f, "20")
		}
	})
}

// Set the model columns to this value
func (m taskMods) UserID(val int64) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.UserID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m taskMods) UserIDFunc(f func() int64) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.UserID = f
	})
}

// Clear any values for the column
func (m taskMods) UnsetUserID() TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.UserID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m taskMods) RandomUserID(f *faker.Faker) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.UserID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m taskMods) CreatedAt(val time.Time) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m taskMods) CreatedAtFunc(f func() time.Time) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m taskMods) UnsetCreatedAt() TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m taskMods) RandomCreatedAt(f *faker.Faker) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m taskMods) UpdatedAt(val time.Time) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m taskMods) UpdatedAtFunc(f func() time.Time) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m taskMods) UnsetUpdatedAt() TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m taskMods) RandomUpdatedAt(f *faker.Faker) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m taskMods) WithParentsCascading() TaskMod {
	return TaskModFunc(func(ctx context.Context, o *TaskTemplate) {
		if isDone, _ := taskWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = taskWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewUserWithContext(ctx, UserMods.WithParentsCascading())
			m.WithUser(related).Apply(ctx, o)
		}
	})
}

func (m taskMods) WithUser(rel *UserTemplate) TaskMod {
	return TaskModFunc(func(ctx context.Context, o *TaskTemplate) {
		o.r.User = &taskRUserR{
			o: rel,
		}
	})
}

func (m taskMods) WithNewUser(mods ...UserMod) TaskMod {
	return TaskModFunc(func(ctx context.Context, o *TaskTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)

		m.WithUser(related).Apply(ctx, o)
	})
}

func (m taskMods) WithExistingUser(em *models.User) TaskMod {
	return TaskModFunc(func(ctx context.Context, o *TaskTemplate) {
		o.r.User = &taskRUserR{
			o: o.f.FromExistingUser(em),
		}
	})
}

func (m taskMods) WithoutUser() TaskMod {
	return TaskModFunc(func(ctx context.Context, o *TaskTemplate) {
		o.r.User = nil
	})
}
