// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Groups = Table[
	groupColumns,
	groupIndexes,
	groupForeignKeys,
	groupUniques,
	groupChecks,
]{
	Schema: "",
	Name:   "groups",
	Columns: groupColumns{
		ID: column{
			Name:      "id",
			DBType:    "bigint",
			Default:   "nextval('groups_id_seq'::regclass)",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Name: column{
			Name:      "name",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp with time zone",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: groupIndexes{
		GroupsPkey: index{
			Type: "btree",
			Name: "groups_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "groups_pkey",
		Columns: []string{"id"},
		Comment: "",
	},

	Comment: "",
}

type groupColumns struct {
	ID        column
	Name      column
	CreatedAt column
	UpdatedAt column
}

func (c groupColumns) AsSlice() []column {
	return []column{
		c.ID, c.Name, c.CreatedAt, c.UpdatedAt,
	}
}

type groupIndexes struct {
	GroupsPkey index
}

func (i groupIndexes) AsSlice() []index {
	return []index{
		i.GroupsPkey,
	}
}

type groupForeignKeys struct{}

func (f groupForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type groupUniques struct{}

func (u groupUniques) AsSlice() []constraint {
	return []constraint{}
}

type groupChecks struct{}

func (c groupChecks) AsSlice() []check {
	return []check{}
}
