// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var GroupErrors = &groupErrors{
	ErrUniqueGroupsPkey: &UniqueConstraintError{
		schema:  "",
		table:   "groups",
		columns: []string{"id"},
		s:       "groups_pkey",
	},
}

type groupErrors struct {
	ErrUniqueGroupsPkey *UniqueConstraintError
}
