// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "github.com/stephenafamo/bob"

// Set the testDB to enable tests that use the database
var testDB bob.Transactor[bob.Tx]

// Make sure the type GroupUser runs hooks after queries
var _ bob.HookableType = &GroupUser{}

// Make sure the type Group runs hooks after queries
var _ bob.HookableType = &Group{}

// Make sure the type Task runs hooks after queries
var _ bob.HookableType = &Task{}

// Make sure the type User runs hooks after queries
var _ bob.HookableType = &User{}
