// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"github.com/stephenafamo/bob/clause"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
)

var (
	SelectWhere     = Where[*dialect.SelectQuery]()
	UpdateWhere     = Where[*dialect.UpdateQuery]()
	DeleteWhere     = Where[*dialect.DeleteQuery]()
	OnConflictWhere = Where[*clause.ConflictClause]() // Used in ON CONFLICT DO UPDATE
)

func Where[Q psql.Filterable]() struct {
	GroupUsers groupUserWhere[Q]
	Groups     groupWhere[Q]
	Tasks      taskWhere[Q]
	Users      userWhere[Q]
} {
	return struct {
		GroupUsers groupUserWhere[Q]
		Groups     groupWhere[Q]
		Tasks      taskWhere[Q]
		Users      userWhere[Q]
	}{
		GroupUsers: buildGroupUserWhere[Q](GroupUsers.Columns),
		Groups:     buildGroupWhere[Q](Groups.Columns),
		Tasks:      buildTaskWhere[Q](Tasks.Columns),
		Users:      buildUserWhere[Q](Users.Columns),
	}
}
