// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// Group is an object representing the database table.
type Group struct {
	ID        int64     `db:"id,pk" `
	Name      string    `db:"name" `
	CreatedAt time.Time `db:"created_at" `
	UpdatedAt time.Time `db:"updated_at" `

	R groupR `db:"-" `
}

// GroupSlice is an alias for a slice of pointers to Group.
// This should almost always be used instead of []*Group.
type GroupSlice []*Group

// Groups contains methods to work with the groups table
var Groups = psql.NewTablex[*Group, GroupSlice, *GroupSetter]("", "groups", buildGroupColumns("groups"))

// GroupsQuery is a query on the groups table
type GroupsQuery = *psql.ViewQuery[*Group, GroupSlice]

// groupR is where relationships are stored.
type groupR struct {
	GroupUsers GroupUserSlice // group_users.group_users_group_id_fkey
}

func buildGroupColumns(alias string) groupColumns {
	return groupColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "name", "created_at", "updated_at",
		).WithParent("groups"),
		tableAlias: alias,
		ID:         psql.Quote(alias, "id"),
		Name:       psql.Quote(alias, "name"),
		CreatedAt:  psql.Quote(alias, "created_at"),
		UpdatedAt:  psql.Quote(alias, "updated_at"),
	}
}

type groupColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         psql.Expression
	Name       psql.Expression
	CreatedAt  psql.Expression
	UpdatedAt  psql.Expression
}

func (c groupColumns) Alias() string {
	return c.tableAlias
}

func (groupColumns) AliasedAs(alias string) groupColumns {
	return buildGroupColumns(alias)
}

// GroupSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type GroupSetter struct {
	ID        omit.Val[int64]     `db:"id,pk" `
	Name      omit.Val[string]    `db:"name" `
	CreatedAt omit.Val[time.Time] `db:"created_at" `
	UpdatedAt omit.Val[time.Time] `db:"updated_at" `
}

func (s GroupSetter) SetColumns() []string {
	vals := make([]string, 0, 4)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s GroupSetter) Overwrite(t *Group) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *GroupSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Groups.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 4)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.Name.IsValue() {
			vals[1] = psql.Arg(s.Name.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[2] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[3] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s GroupSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s GroupSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 4)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindGroup retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindGroup(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*Group, error) {
	if len(cols) == 0 {
		return Groups.Query(
			sm.Where(Groups.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Groups.Query(
		sm.Where(Groups.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Groups.Columns.Only(cols...)),
	).One(ctx, exec)
}

// GroupExists checks the presence of a single record by primary key
func GroupExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return Groups.Query(
		sm.Where(Groups.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Group is retrieved from the database
func (o *Group) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Groups.AfterSelectHooks.RunHooks(ctx, exec, GroupSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Groups.AfterInsertHooks.RunHooks(ctx, exec, GroupSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Groups.AfterUpdateHooks.RunHooks(ctx, exec, GroupSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Groups.AfterDeleteHooks.RunHooks(ctx, exec, GroupSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Group
func (o *Group) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Group) pkEQ() dialect.Expression {
	return psql.Quote("groups", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Group
func (o *Group) Update(ctx context.Context, exec bob.Executor, s *GroupSetter) error {
	v, err := Groups.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Group record with an executor
func (o *Group) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Groups.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Group using the executor
func (o *Group) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Groups.Query(
		sm.Where(Groups.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after GroupSlice is retrieved from the database
func (o GroupSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Groups.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Groups.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Groups.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Groups.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o GroupSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("groups", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o GroupSlice) copyMatchingRows(from ...*Group) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o GroupSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Groups.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Group:
				o.copyMatchingRows(retrieved)
			case []*Group:
				o.copyMatchingRows(retrieved...)
			case GroupSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Group or a slice of Group
				// then run the AfterUpdateHooks on the slice
				_, err = Groups.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o GroupSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Groups.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Group:
				o.copyMatchingRows(retrieved)
			case []*Group:
				o.copyMatchingRows(retrieved...)
			case GroupSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Group or a slice of Group
				// then run the AfterDeleteHooks on the slice
				_, err = Groups.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o GroupSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals GroupSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Groups.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o GroupSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Groups.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o GroupSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Groups.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// GroupUsers starts a query for related objects on group_users
func (o *Group) GroupUsers(mods ...bob.Mod[*dialect.SelectQuery]) GroupUsersQuery {
	return GroupUsers.Query(append(mods,
		sm.Where(GroupUsers.Columns.GroupID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os GroupSlice) GroupUsers(mods ...bob.Mod[*dialect.SelectQuery]) GroupUsersQuery {
	pkID := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "bigint[]")),
	))

	return GroupUsers.Query(append(mods,
		sm.Where(psql.Group(GroupUsers.Columns.GroupID).OP("IN", PKArgExpr)),
	)...)
}

type groupWhere[Q psql.Filterable] struct {
	ID        psql.WhereMod[Q, int64]
	Name      psql.WhereMod[Q, string]
	CreatedAt psql.WhereMod[Q, time.Time]
	UpdatedAt psql.WhereMod[Q, time.Time]
}

func (groupWhere[Q]) AliasedAs(alias string) groupWhere[Q] {
	return buildGroupWhere[Q](buildGroupColumns(alias))
}

func buildGroupWhere[Q psql.Filterable](cols groupColumns) groupWhere[Q] {
	return groupWhere[Q]{
		ID:        psql.Where[Q, int64](cols.ID),
		Name:      psql.Where[Q, string](cols.Name),
		CreatedAt: psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt: psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *Group) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "GroupUsers":
		rels, ok := retrieved.(GroupUserSlice)
		if !ok {
			return fmt.Errorf("group cannot load %T as %q", retrieved, name)
		}

		o.R.GroupUsers = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Group = o
			}
		}
		return nil
	default:
		return fmt.Errorf("group has no relationship %q", name)
	}
}

type groupPreloader struct{}

func buildGroupPreloader() groupPreloader {
	return groupPreloader{}
}

type groupThenLoader[Q orm.Loadable] struct {
	GroupUsers func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildGroupThenLoader[Q orm.Loadable]() groupThenLoader[Q] {
	type GroupUsersLoadInterface interface {
		LoadGroupUsers(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return groupThenLoader[Q]{
		GroupUsers: thenLoadBuilder[Q](
			"GroupUsers",
			func(ctx context.Context, exec bob.Executor, retrieved GroupUsersLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadGroupUsers(ctx, exec, mods...)
			},
		),
	}
}

// LoadGroupUsers loads the group's GroupUsers into the .R struct
func (o *Group) LoadGroupUsers(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.GroupUsers = nil

	related, err := o.GroupUsers(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Group = o
	}

	o.R.GroupUsers = related
	return nil
}

// LoadGroupUsers loads the group's GroupUsers into the .R struct
func (os GroupSlice) LoadGroupUsers(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	groupUsers, err := os.GroupUsers(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.GroupUsers = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range groupUsers {

			if !(o.ID == rel.GroupID) {
				continue
			}

			rel.R.Group = o

			o.R.GroupUsers = append(o.R.GroupUsers, rel)
		}
	}

	return nil
}

type groupJoins[Q dialect.Joinable] struct {
	typ        string
	GroupUsers modAs[Q, groupUserColumns]
}

func (j groupJoins[Q]) aliasedAs(alias string) groupJoins[Q] {
	return buildGroupJoins[Q](buildGroupColumns(alias), j.typ)
}

func buildGroupJoins[Q dialect.Joinable](cols groupColumns, typ string) groupJoins[Q] {
	return groupJoins[Q]{
		typ: typ,
		GroupUsers: modAs[Q, groupUserColumns]{
			c: GroupUsers.Columns,
			f: func(to groupUserColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, GroupUsers.Name().As(to.Alias())).On(
						to.GroupID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
