// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// Task is an object representing the database table.
type Task struct {
	ID        int64     `db:"id,pk" `
	Name      string    `db:"name" `
	UserID    int64     `db:"user_id" `
	CreatedAt time.Time `db:"created_at" `
	UpdatedAt time.Time `db:"updated_at" `

	R taskR `db:"-" `
}

// TaskSlice is an alias for a slice of pointers to Task.
// This should almost always be used instead of []*Task.
type TaskSlice []*Task

// Tasks contains methods to work with the tasks table
var Tasks = psql.NewTablex[*Task, TaskSlice, *TaskSetter]("", "tasks", buildTaskColumns("tasks"))

// TasksQuery is a query on the tasks table
type TasksQuery = *psql.ViewQuery[*Task, TaskSlice]

// taskR is where relationships are stored.
type taskR struct {
	User *User // tasks.tasks_user_id_fkey
}

func buildTaskColumns(alias string) taskColumns {
	return taskColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "name", "user_id", "created_at", "updated_at",
		).WithParent("tasks"),
		tableAlias: alias,
		ID:         psql.Quote(alias, "id"),
		Name:       psql.Quote(alias, "name"),
		UserID:     psql.Quote(alias, "user_id"),
		CreatedAt:  psql.Quote(alias, "created_at"),
		UpdatedAt:  psql.Quote(alias, "updated_at"),
	}
}

type taskColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         psql.Expression
	Name       psql.Expression
	UserID     psql.Expression
	CreatedAt  psql.Expression
	UpdatedAt  psql.Expression
}

func (c taskColumns) Alias() string {
	return c.tableAlias
}

func (taskColumns) AliasedAs(alias string) taskColumns {
	return buildTaskColumns(alias)
}

// TaskSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type TaskSetter struct {
	ID        omit.Val[int64]     `db:"id,pk" `
	Name      omit.Val[string]    `db:"name" `
	UserID    omit.Val[int64]     `db:"user_id" `
	CreatedAt omit.Val[time.Time] `db:"created_at" `
	UpdatedAt omit.Val[time.Time] `db:"updated_at" `
}

func (s TaskSetter) SetColumns() []string {
	vals := make([]string, 0, 5)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if s.UserID.IsValue() {
		vals = append(vals, "user_id")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s TaskSetter) Overwrite(t *Task) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if s.UserID.IsValue() {
		t.UserID = s.UserID.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *TaskSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Tasks.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 5)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.Name.IsValue() {
			vals[1] = psql.Arg(s.Name.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.UserID.IsValue() {
			vals[2] = psql.Arg(s.UserID.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[3] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[4] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s TaskSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s TaskSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 5)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.UserID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_id")...),
			psql.Arg(s.UserID),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindTask retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindTask(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*Task, error) {
	if len(cols) == 0 {
		return Tasks.Query(
			sm.Where(Tasks.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Tasks.Query(
		sm.Where(Tasks.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Tasks.Columns.Only(cols...)),
	).One(ctx, exec)
}

// TaskExists checks the presence of a single record by primary key
func TaskExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return Tasks.Query(
		sm.Where(Tasks.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Task is retrieved from the database
func (o *Task) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Tasks.AfterSelectHooks.RunHooks(ctx, exec, TaskSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Tasks.AfterInsertHooks.RunHooks(ctx, exec, TaskSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Tasks.AfterUpdateHooks.RunHooks(ctx, exec, TaskSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Tasks.AfterDeleteHooks.RunHooks(ctx, exec, TaskSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Task
func (o *Task) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Task) pkEQ() dialect.Expression {
	return psql.Quote("tasks", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Task
func (o *Task) Update(ctx context.Context, exec bob.Executor, s *TaskSetter) error {
	v, err := Tasks.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Task record with an executor
func (o *Task) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Tasks.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Task using the executor
func (o *Task) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Tasks.Query(
		sm.Where(Tasks.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after TaskSlice is retrieved from the database
func (o TaskSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Tasks.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Tasks.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Tasks.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Tasks.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o TaskSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("tasks", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o TaskSlice) copyMatchingRows(from ...*Task) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o TaskSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Tasks.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Task:
				o.copyMatchingRows(retrieved)
			case []*Task:
				o.copyMatchingRows(retrieved...)
			case TaskSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Task or a slice of Task
				// then run the AfterUpdateHooks on the slice
				_, err = Tasks.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o TaskSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Tasks.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Task:
				o.copyMatchingRows(retrieved)
			case []*Task:
				o.copyMatchingRows(retrieved...)
			case TaskSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Task or a slice of Task
				// then run the AfterDeleteHooks on the slice
				_, err = Tasks.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o TaskSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals TaskSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Tasks.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o TaskSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Tasks.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o TaskSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Tasks.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// User starts a query for related objects on users
func (o *Task) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.UserID))),
	)...)
}

func (os TaskSlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkUserID := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkUserID = append(pkUserID, o.UserID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkUserID), "bigint[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachTaskUser0(ctx context.Context, exec bob.Executor, count int, task0 *Task, user1 *User) (*Task, error) {
	setter := &TaskSetter{
		UserID: omit.From(user1.ID),
	}

	err := task0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachTaskUser0: %w", err)
	}

	return task0, nil
}

func (task0 *Task) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachTaskUser0(ctx, exec, 1, task0, user1)
	if err != nil {
		return err
	}

	task0.R.User = user1

	user1.R.Tasks = append(user1.R.Tasks, task0)

	return nil
}

func (task0 *Task) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachTaskUser0(ctx, exec, 1, task0, user1)
	if err != nil {
		return err
	}

	task0.R.User = user1

	user1.R.Tasks = append(user1.R.Tasks, task0)

	return nil
}

type taskWhere[Q psql.Filterable] struct {
	ID        psql.WhereMod[Q, int64]
	Name      psql.WhereMod[Q, string]
	UserID    psql.WhereMod[Q, int64]
	CreatedAt psql.WhereMod[Q, time.Time]
	UpdatedAt psql.WhereMod[Q, time.Time]
}

func (taskWhere[Q]) AliasedAs(alias string) taskWhere[Q] {
	return buildTaskWhere[Q](buildTaskColumns(alias))
}

func buildTaskWhere[Q psql.Filterable](cols taskColumns) taskWhere[Q] {
	return taskWhere[Q]{
		ID:        psql.Where[Q, int64](cols.ID),
		Name:      psql.Where[Q, string](cols.Name),
		UserID:    psql.Where[Q, int64](cols.UserID),
		CreatedAt: psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt: psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *Task) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("task cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.Tasks = TaskSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("task has no relationship %q", name)
	}
}

type taskPreloader struct {
	User func(...psql.PreloadOption) psql.Preloader
}

func buildTaskPreloader() taskPreloader {
	return taskPreloader{
		User: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](psql.PreloadRel{
				Name: "User",
				Sides: []psql.PreloadSide{
					{
						From:        Tasks,
						To:          Users,
						FromColumns: []string{"user_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
	}
}

type taskThenLoader[Q orm.Loadable] struct {
	User func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildTaskThenLoader[Q orm.Loadable]() taskThenLoader[Q] {
	type UserLoadInterface interface {
		LoadUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return taskThenLoader[Q]{
		User: thenLoadBuilder[Q](
			"User",
			func(ctx context.Context, exec bob.Executor, retrieved UserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadUser loads the task's User into the .R struct
func (o *Task) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Tasks = TaskSlice{o}

	o.R.User = related
	return nil
}

// LoadUser loads the task's User into the .R struct
func (os TaskSlice) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.UserID == rel.ID) {
				continue
			}

			rel.R.Tasks = append(rel.R.Tasks, o)

			o.R.User = rel
			break
		}
	}

	return nil
}

type taskJoins[Q dialect.Joinable] struct {
	typ  string
	User modAs[Q, userColumns]
}

func (j taskJoins[Q]) aliasedAs(alias string) taskJoins[Q] {
	return buildTaskJoins[Q](buildTaskColumns(alias), j.typ)
}

func buildTaskJoins[Q dialect.Joinable](cols taskColumns, typ string) taskJoins[Q] {
	return taskJoins[Q]{
		typ: typ,
		User: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.UserID),
					))
				}

				return mods
			},
		},
	}
}
